
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 02 13:17:10 CET 2013
//----------------------------------------------------

package de.dhbw.blaaah.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 16;
  public static final int FROM = 3;
  public static final int SEMICOLON = 18;
  public static final int SELECT = 2;
  public static final int EQUAL = 19;
  public static final int DATE = 24;
  public static final int STAR = 17;
  public static final int VALUE = 14;
  public static final int NAME = 13;
  public static final int TABLE = 5;
  public static final int LEFT_PARENTHESIS = 20;
  public static final int CREATE = 4;
  public static final int COMMA = 12;
  public static final int RIGHT_PARENTHESIS = 21;
  public static final int INSERT = 6;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int VALUES = 15;
  public static final int SET = 9;
  public static final int DROP = 11;
  public static final int error = 1;
  public static final int TEXT = 23;
  public static final int DELETE = 10;
  public static final int UPDATE = 8;
  public static final int INTO = 7;
}

